class PostsController < ApplicationController
  def show
  #find the post that corresponds to the id in the params that was passed to show and assign it to @post
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
  #creating instance variable, then assign it an empty post returned by Post.new
    @post = Post.new
  end

  def create
  #call Post.new to create a new instance of Post
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])

    @post.topic = @topic

  #successfully save Post to database, display success message and redirect the user to route generated by @post
    if @post.save
      #assign value to flash[:notice], flash hash provides a way to pass temporary values between actions
      #value placed in flash will be available in next action and then deleted
      flash[:notice] = "Post was saved"
      redirect_to [@topic, @post]
    else

      #if unsuccessful in saving Post to database, we display an error message and render new view again
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

#
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting that post. Please try again."
      render :show
    end
  end
end
